Python 3.7 regex bug fixed
Added py37 to tox environment list.

It finds an error with my previous PR:

The docs show a change in `Pattern.sub`.
```
Changed in version 3.7: Unknown escapes in repl consisting of '\' and an ASCII letter now are errors.
```

```
>>> import re
>>> DOLLAR_FINDER = re.compile(r"(?<!\\)\$")
>>> DOLLAR_FINDER.sub(r'\Z', 'hello$')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\Z'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/local/lib/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/local/lib/python3.7/sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \Z at position 0
>>> DOLLAR_FINDER.sub(r'\\Z', 'hello$')
'hello\\Z'
```